### ISSUE TITLE
Top bar is still shown in fullscreen apps

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1081]
### Steps to Reproduce 
1  Download a fullscreen app I.e. Pathwind Fork
2. Open the app

### Expected Results 
The appeared covers the whole screen.

### Actual Results 
The top bar is still shown and the app's bottom part is cut off.

**Comment by pixelr0** [comment]
same with balls

**Comment by mateosalta** [comment]
oh, that happened with some webapps awhile back when updating the toolkit, I think the header bar was shown explicitly, even if you didin't put it in, had to put the element in just to say it was 0 height, or not visible

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/144

**Comment by kugiigi** [comment]
This doesn't seem to be fixed yet as shown in the screenshot below.
Instead of being in fullscreen, the top bar is still shown and the app is a bit moved towards the bottom.

![screenshot20190608_145136237](https://user-images.githubusercontent.com/29456786/59143441-d2ed2980-89fd-11e9-8a5b-5ae90f13798f.png)

**Comment by pixelr0** [comment]
yeah, same here, fp2

**Comment by UniversalSuperBox** [comment]
It doesn't appear that that app should be fullscreen, but you're right, it is pushed down. Does it actually dismiss the top bar when a fullscreen video opens?

**Comment by kugiigi** [comment]
The app should actually be in full screen as it is in other channels. And nope, full screen videos are still pushed down and top bar is still visible.

**Comment by pixelr0** [comment]
try with balls2 game (should be full screen)

**Comment by mateosalta** [comment]
yeah, the youtube webapp is in fullscreen all the time right now... need to update it now that someone has working fullscreen mode.

**Comment by NeoTheThird** [comment]
Still an issue with pathwind. Also see https://github.com/ubports/morph-browser/issues/202 for browser-related weirdness.

**Comment by mariogrip** [comment]
I guess whats happening here is that it does not respect first initial fullscreen request

**Comment by mariogrip** [comment]
Note on balls2: it seems like the client itself is requesting restored state, thats why i used so long on this issue, i used that app to debug it...

see: https://paste.ubuntu.com/p/bP8cTwcxZK/
as you can see on line 80:
```
<information> miral::Window Management: handle_modify_window window_info={name=Balls 2, type=normal, state=fullscreen, top_left=(0, 0), size=(1080, 1857), restore_rect=((0, 0), (1080, 1857)), children={}, preferred_orientation=0xf, confine_pointer=0, output_id=0}, modifications={top_left=(0, 0), size=(1080, 1857), state=restored}
```
this modification does not happen from the server side. 
It the server was to modify, it would use `invoke_under_lock` (see qtmir)

so the fix above does not fix balls2, but it seems to be a  seems to be a client bug, so we cant do anything about that. maybe a sdl2 bug?

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/172
