### ISSUE TITLE
Last updated date incorrect

### ISSUE THREAD

**Issue by jmbell128** [ubports/ubuntu-touch#1128]
### Illustrations

- Device: Bacon
- Channel: Development
- Build: Version 855 / Ubuntu 16.04 (2019-05-02/2)

### Steps to reproduce

Update to version 855
Go to System Settings > About
Look under Software section at Last Updated date

### Expected behavior

Show the correct date

### Actual behavior

Same steps in reproduction but the displayed date is incorrect. In my case it shows 12/28/73

### Logfiles and additional information

None. Unsure of which logs to pull.

**Comment by JulienPeloton** [comment]
Environment:
* Device: Nexus 5
* Channel: rc
* Build: 2019-18

### actual behaviour

I also observe wrong update dates on my N5 (but differently from reported above). The date for the last release gets updated every day, while the date for the Nth-1 release stops getting updated when I switch to the Nth release.

### expected behaviour

The update date should be the unique date when the image has been updated.

Below is a screenshot of the current situation (Version 43 was put on May 1st, and Version 42 was put sometimes in April):

![screenshot20190502_233343152](https://user-images.githubusercontent.com/20426972/57108531-55196c80-6d33-11e9-8bdb-ce7bc4271417.png)

**Comment by jmbell128** [comment]
Confirmed that the error in the dates are in different locations. What tool did you use for the screenshot? I installed Ubuntu Touch yesterday and haven't had a chance to figure everything out yet.

**Comment by JulienPeloton** [comment]
On the nexus 5, screenshots are done pressing Volume UP+DOWN simultaneously. Not sure if this will be the same for your device though.

**Comment by jmbell128** [comment]
Just tried it, it's the same on both devices. Censored some sensetive info in my screenshot, the incorrect date is in the section below it. 
![screenshot20190502_183653846-2](https://user-images.githubusercontent.com/15852322/57111800-87af6f00-6d0b-11e9-96bd-0180b5c442a2.png)

**Comment by jmbell128** [comment]
Issue persists to Version 856

**Comment by Flohack74** [comment]
Please 1) stop reporting, as this is a known bug, 2) search the issue tracker for the first report of this, I am 100% sure this is a duplicate.

**Comment by jmbell128** [comment]
Duplicate of #685 

@Flohack74 Thank you. I tried searching the issue tracker before but couldn't find anything (More than likely due to a typo or filter I used). I did as you asked and found it.

I'm new to bug reporting so if you'll forgive my ignorant question, why is the issue closed if the problem still persists?

**Comment by Flohack74** [comment]
Ok I checked this now on my OPO, and there the date is correct. Thats an interesting one. The old bug was closed because apparently it was fixed. But not for all of us? No idea...

Sorry I confused it with the last update date not correct in the actual "Updates" section, there you will notice that the last update shows the date of the last-last update :)

**Comment by TiceRex** [comment]
This problem still exists on a fresh install (Nexus 5, 16.04 stable OTA-13).
After the first boot it shows the correct date, but after a restart it shows a wrong date.

![screenshot20200922_081057186](https://user-images.githubusercontent.com/6769841/93857026-3ade8680-fcba-11ea-968c-846b15f654fc.png)

![screenshot20200922_081524470](https://user-images.githubusercontent.com/6769841/93857044-429e2b00-fcba-11ea-8e12-be94c11aebf2.png)
