### ISSUE TITLE
Input text field not emptied after sending SMS

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#1152]
- Device: Turbo
- Channel: Devel
- Build: 319

### Steps to reproduce
Enter a text message in the messaging app and press the send button.

### Expected behavior
Messaging text field emptied

### Actual behavior
Message is sent, but text remains in the input text field

**Comment by ChristianPauly** [comment]
Already fixed here: https://github.com/ubports/messaging-app/pull/109

**Comment by UniversalSuperBox** [comment]
Fixed in ubports/messaging-app#109

**Comment by RitterDerEhre** [comment]
There are reports that the problem still exists in OTA10 stable and RC55.
