### ISSUE TITLE
Apps gets started in the background behind other running apps

### ISSUE THREAD

**Issue by mauricioduarte01** [ubports/ubuntu-touch#1210]
- Device: all
- Channel: Edge 
- Build: 2019-08-27

### Steps to reproduce
Have an application running and try to open a new app. 

### Expected behavior
The new App needs to take focus over the previous opened app.

### Actual behavior
When I start an app from the drawer in edge, the app gets started in the background, behind other already running apps. I have to open the app-spread to find the app. (luksus)

**Comment by lduboeuf** [comment]
confirmed on N5 for me as well

**Comment by lduboeuf** [comment]
which logs should we provide ? Or maybe already have idees where it is ?

**Comment by kugiigi** [comment]
This seems to be a duplicate of #1170 ?

**Comment by mariogrip** [comment]
Fixed with: https://github.com/ubports/unity8/pull/177

**Comment by lduboeuf** [comment]
it happens again on last revision for me (N5)

**Comment by Danfro** [comment]
This does still happen on devel on various devices.
We did some testing for a pattern on this one in the QA group and found a pattern:

Apps do only open in the background when the drawer is open.
If only the launcher is open, apps do open in foreground.
Hope this helps searching for a fix.
