### ISSUE TITLE
Edge: lower part of launcher not accessible when OSK is raised

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1245]
Device: E5
Channel: edge
Build: 2019-10-04 (v163)

Steps to reprocuce:
- open launcher
- type something in search bar to raise the OSK
- swipe the launcher towards the icons in the lower part of the launcher

Expected behaviour:
- all icons can be reached

Current behaviour:
- the lower icons are hidden behind the OSK, the launcher can not be scrolled low enough to reach them

Possible solutions:
- When the launcher gets the focus OR when the search bar looses the focus the OSK is dismissed
- The launcher is resized so its bottom matches top of OSK

**Comment by Danfro** [comment]
somehow related to #1238

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/unity8/pull/206

**Comment by Danfro** [comment]
This is NOT fixed on my E5 in dev channel.

When the OSK is open scrolling the launcher does not close the OSK. The lower part is still not accessible.
