### ISSUE TITLE
Wifi continuosly crashing after trying to upgrade to OTA-11 with Anbox installed

### ISSUE THREAD

**Issue by tallero** [ubports/ubuntu-touch#1280]
When I switched to `dev` last month I unsuccessfully tried installing anbox and I got this bug in which cellular connection was continuously crashing, rendering the phone sluggish to the point it was not usable. 
Then I came back to stable and reinstalled anbox (this time it is working).
Now I have stable to OTA-11 (version 9?) and the same issue but with wifi. If I disable wifi with

    nmcli n off

the service stops crashing but of course I am not connected to anything.
Also, it does not stop if I give

    nmcli r all off

In general it seems like network manager manages connections but not entirely and in general is not completely *paired* with the UI. Ifconfig does not report any device apart from loop device and `anbox0`.

- Device: Hammerhead
- Channel: stable
- Build: OTA-11

### Steps to reproduce
Upgrade Nexus 5 to OTA-11 without reflashing `anbox-$devicename.img`.

### Expected behavior
Wifi see connections and I can connect to them.

### Actual behavior
Wifi controls crash every few seconds

### Logfiles and additional information
Reflashing `anbox-$devicename.img` will solve the problem.

So, no network device detecting is an example of the possible *unstable states* cited on the [docs](http://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html) [#262](https://github.com/ubports/docs.ubports.com/pull/262).

**Comment by tallero** [comment]
Stable version bug of #1264.

**Comment by BadAngelZ** [comment]
Hi !
You wrote: 

> Reflashing anbox-$devicename.img will solve the problem.

Do you mean that if I flash the anbox-$devicename.img twice it may solve the problem ? I should give it a try ...

**Comment by tallero** [comment]
I had `anbox` installed when I did the upgrade and this happened.

Some weeks ago I tried `dev` and I had no problems before installing `anbox`. Because in any case I had to flash the boot img to keep using android apps, I tried it and it worked.

**Comment by tallero** [comment]
Actually it seems that the upgrade did not happen. 

After re-flashing anbox boot img and so recovering network stack, the updater notifies again that version 9 of "Ubuntu Touch" being available.

I tried re-doing the upgrade but it happened the same.

**Comment by aetherfaerber** [comment]
Hi,
I also don't really understand how to fix this. Here what I did:

1. have anbox installed and active
2. receive update to OTA-11 on the «stable» channel
3. have a device burning all its power and being unresponsive
4. use “nmcli n off“ to get back control
5. reflash anbox

now I seem to have the same situation as described in #1264 – no wifi hardware detected as shown by “nmcli -p d“

Can this be fixed by doing an “anbox-tool ugrade”? It takes ages via the mobile connection but seems more bearable in comparison to a new system update.

**Comment by Flohack74** [comment]
Please have a little patience, the fix is being prepared and will then be in the devel channel. It should be good to just switch there when its ready.

**Comment by aetherfaerber** [comment]
Thanks for the fix and the fast reply. Tbh I feel reluctant to run a devel channel on my phone. The reason I use ubports is because I didn't expect any big reliability gaps until xenial's eol.
Do I understand correctly that it is easy to switch back from devel to rc and back to stable once releases come out? If devel -> rc is harder than rc -> stable I also easily could hold out another week without a working phone.

**Comment by Flohack74** [comment]
The bug is now fixed and confirmed in #1264 - Please see comment here for a possible solution for stable: https://github.com/ubports/ubuntu-touch/issues/1264#issuecomment-560520664 - You could download our daily-hammerhead tar file and extract the boot partition and flash it via fastboot. That would allow you to stay on stable but get a new kernel.

**Comment by aetherfaerber** [comment]
Thank you again!
Sadly, this doesn't seem to work for me. I flashed the boot partition from daily and according to uname -a now have last nights kernel. Wifi still crashes and is unavailable after I reactivated it with 'nmcli n on'.

**Comment by tallero** [comment]
I believe you have to first switch to devel first, maybe you can't flash devel kernel img on stable rootfs.

**Comment by aetherfaerber** [comment]
@tallero thanks again for your answer. I don't really see what switching to devel should change – do you suggest there are kernel features that are supported in devel but not in stable? 
As I already said: I *am* running the kernel built on December 3.

**Comment by Flohack74** [comment]
We updated the "normal" kernel with that feature, so if you install devel channel with the installer and bootstrap option checked, you should get this kernel. After that, you can switch to any channel again without bootstrapping, and it should persist.
I have no idea why that method, or even taking the boot.img from our CI server should not solve the issue, but maybe its worth retrying a manual flash with fastboot.
So please try:
- Download https://ci.ubports.com/job/daily-hammerhead/ - any recent job from today or so will do it.
- Extract partitions/boot.img
- Use adb reboot bootloader to get in fastboot mode
- fastboot flash boot boot.img
- fastboot reboot

Tell us if that works.

**Comment by mariogrip** [comment]
that wont work, as the wifi module is built in to the android container, so system.img also has to be changed for wifi to work.

**Comment by aetherfaerber** [comment]
Thank you again @flohack74 – also for the detailed instructions. Alas,
that is exactly what I had done before and as @mariogrip pointed out,
it did not fix the situation.

I tried exchanging the system.img (/var/lib/lxc/android/system.img
from the daily image) but rendered my system unbootable – no space
left on device).
For now I went back to the previous stable release, thereby getting rid
of anbox. WiFi is controllable via nmcli once more.

Thanks again!

**Comment by Flohack74** [comment]
Ok then this bug is unfixable until next OTA.

**Comment by tallero** [comment]
If someone still wants to use anbox on `devel`, I got this working simply switching to it from a `stable` OTA-10` and then flashing the latest CI kernel build.

**Comment by Flohack74** [comment]
Can we put this into QA state for OTA-12, even though it affects also stable users? I think we should close this soonish to get OTA-12 moving a bit faster...

**Comment by mariogrip** [comment]
Yup, can close this now
