### ISSUE TITLE
Oneplus one: Cannot mount MTP

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#13]
r267
devel_rc-proposed

What happens:
Plugging in the Oneplus one to an Ubuntu computer does not mount or allow MTP.

Expected:
Being able to brows the phone contents with nautilus

It's possible that https://bugs.launchpad.net/ubports-fp2/+bug/1669905 is related to this bug.

Reported by https://launchpad.net/~joe.

**Comment by tomoqv** [comment]
Seems related to my bug here: https://github.com/ubports/ubports-touch/issues/11

**Comment by tomoqv** [comment]
Yes, and I should add that my OPO is only visible to a PC with developer mode off, but it still doesn't mount. Turning developer mode on, it is not even visible through lsusb.

**Comment by tomoqv** [comment]
On 15.04/devel r10 I can finally mount my OPO, but only if I have developer mode set to disabled. When enabling developer mode, the device can't mount again. Seems like the dev mode settings button is inverted.
Regardless of developer mode setting, the device does not expose an adb interface.

**Comment by mariogrip** [comment]
Fix released: https://github.com/ubports/device-files/commit/2d65b596a9e5b9e9b02263c3b4bb0f76a18d25b5 and https://github.com/ubports/build-scripts/commit/9c0f53526ef844d392bbb24f293796a1b5bc9b84

**Comment by tomoqv** [comment]
This bug appears to have resurfaced lately. I noticed it today on devel r146. Reboot didn't fix it. Last time I connected my OPO to this PC it worked, but it may have been a couple of weeks ago.

**Comment by tomoqv** [comment]
What is happening with this? Unfortunate regression of a function that is rather essential. I would very much like to have it back.

**Comment by tomoqv** [comment]
Just to further some information on this issue.
Following shows in terminal when OPO (developer mode on) connected to my PC:
```
...:~$ lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 8087:0a2a Intel Corp. 
Bus 002 Device 004: ID 04f2:0111 Chicony Electronics Co., Ltd KU-9908 Keyboard
Bus 002 Device 003: ID 05c6:6765 Qualcomm, Inc. 
Bus 002 Device 002: ID 045e:00d2 Microsoft Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
Dito with developer mode off:
```
...:~$ lsusb
Bus 001 Device 002: ID 8087:8001 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 005: ID 8087:0a2a Intel Corp. 
Bus 002 Device 004: ID 04f2:0111 Chicony Electronics Co., Ltd KU-9908 Keyboard
Bus 002 Device 006: ID 05c6:6764 Qualcomm, Inc. A0001 Phone [OnePlus One]
Bus 002 Device 002: ID 045e:00d2 Microsoft Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
Below still with developer mode off:
```
...:~$ adb devices
List of devices attached 
...:~$ adb shell
error: device not found
...:~$ adb devices
```
And with developer mode on:
```
List of devices attached 
d9a48603	offline
```

**Comment by tomoqv** [comment]
I have checked all the steps from this bug report: https://github.com/ubports/ubports-touch/issues/11

**Comment by tomoqv** [comment]
Yeah, and once in a while I get:
```
...:~$ adb devices
List of devices attached 
d9a48603	offline
```
Then I can do `adb pull /home/phablet/whatever_file`, but MTP still doesn't work.

**Comment by tomoqv** [comment]
With devel r170 (today) there is some progress. Still no MTP, but I can now adb shell into the device again.

**Comment by tomoqv** [comment]
I can see that this is still marked as "needs confirmation". Does that mean it works on other OPOs? The problem persists for me in devel r203.

**Comment by Voltcab** [comment]
Hello, yes, I have the same problem. My phone is recognized but it is impossible to open it on my PC. I can't transfer my files. I will follow with you the evolution. I hope there will be a quick solution...

**Comment by stekalb** [comment]
Also an issue on my bacon. (r204)

**Comment by BlueKenny** [comment]
Same issue on my phone

**Comment by andybleaden** [comment]
I can confirm this is still a bug. Not how I can help but happy to try. This has been fixed previously I know but keeps cropping up. Not sure why

**Comment by chakare** [comment]
current build number: 118
device name: bacon
channel: ubports-touch/16.04/devel

upstart detects USB connected, try to start the mtp-server but fails to open RW the /dev/mtp_usb device

ll /dev/mtp_usb 
crw-rw---- 1 root root 10, 53 Aug 13  1972 /dev/mtp_usb

so, this device needs root:phablet permissions.

**Comment by Pete413** [comment]
Is there any solution to the problem? I flashed today an OnePlusOne with Ubuntu Touch (stable) and I get the same problem. I see the device "bacon" in Nautilus file manager, but clicking on it leads to an MTP error.

**Comment by Flohack74** [comment]
I can confirm the issue is gone with changing the group permissions. While looking for a permanent solution a `su chown root:phablet /dev/mtp_usb `makes a temporary fix ;)

**Comment by andybleaden** [comment]
Oh your joking...is it that easy?

Thanks...I can reinstall and get back to Ubuntu Touch on my OPO.  Yippee

**Comment by Pete413** [comment]
Thanks flohack for the workaround.

What am I doing wrong? After "sudo chown root:phablet /dev/mtp_usb" I get following error message:
"chown: invalid group: ‘root:phablet’ "

Thanks!

**Comment by Flohack74** [comment]
@Pete413 try root:plugdev plz

**Comment by Pete413** [comment]
Dear Flohack. Thanks, this solved half of the issue, but I unfortunately is not the full solution:

The following command accepts plugdev, but does not find the mtp_usb device:
> sudo chown root:plugdev /dev/mtp_usb
chown: cannot access '/dev/mtp_usb': No such file or directory

I tried several devices in /dev, but could not find any practicable solution. Only the following command did not give an error message, but it also did not solve my problem, unfortunately.
> sudo chown root:plugdev /dev/bus/usb/003/017

Thanks.

**Comment by Flohack74** [comment]
@Pete413 Can you check for me if you got original bacon or A0001 as device identifier? There are several OPO models obviously out there...

**Comment by Pete413** [comment]
@Flohack74 On the device paper box, it says OnePlus One A0001 (Sandstone Black). In UBPorts "About the phone" is simply says OnePlus bacon. In syslog (after plugging in the USB cable), it says idVendor=05c6, idProduct=6765, Product: bacon, Manufacturer: OnePlus, SerialNumber: 8e244882.

By the way: My system is Ubuntu 16.04 and USB/MTP connections with the devices BQ M10 and BQ 4.5 work without any problems.

**Comment by Flohack74** [comment]
@Pete413 Intersting, I also got the A0001 version. I got this device :) - I will investigate with @mariogrip what his opinion is ;)

**Comment by Pete413** [comment]
@Flohack74 Thanks for your help and the patch. Will this new udev rule also "create" the /dev/mtp_usb device in dev when plugging in the smartphone? (Currently, without this udev rule I get the error "No such file or directory" indicating the missing /dev/mtp_usb)

**Comment by Flohack74** [comment]
A How-To for 15.04 to make the change permanent: https://forums.ubports.com/topic/1015/howto-opo-fix-mtp-driver-permissions

**Comment by Flohack74** [comment]
@Pete413 that sounds interesting, no, this should be there already. Dunno why it would not.
