### ISSUE TITLE
Camera app freezes when recording video

### ISSUE THREAD

**Issue by Charadon** [ubports/ubuntu-touch#1521]
- Device: Nexus 5 ( Hammerhead ) 
- Channel: rc
- Build: 2020-W29

### Steps to reproduce
Open camera app, switch to video mode, then tap the record button.

### Expected behavior
Video records, and saves video.

### Actual behavior
App freezes and video cannot be made

### Logfiles and additional information

    ** Application is now active
     
    virtual QSGVideoNode* ShaderVideoNodePlugin::createNode(const QVideoSurfaceFormat&)
     
    Already have a texture id and video sink, not creating a new one
     
    shm_open() failed: Permission denied
     
    QObject::killTimer: Timers cannot be stopped from another thread
     
    QObject::startTimer: Timers cannot be started from another thread

**Comment by amebablues-nexus** [comment]
Devel channel happens the same thing. Using current - 30.07.2020

**Comment by gbdomubpkm** [comment]
I noticed that today on OPO dev 1543
Doesn't affect BQ E5 HD dev

**Comment by amebablues-nexus** [comment]
I updated today. Still remais the same bug.

**Comment by amebablues-nexus** [comment]
Devel xhannel updated today. Same problem here.

**Comment by C0n57an71n** [comment]
With the OTA13, the camera behaves like before: the only freeze is when changing from picture to video mode, but in video mode I have never experienced freeze, nor now or before.

**Comment by Flohack74** [comment]
@C0n57an71n so are you saying that it is fixed, or not ;)

**Comment by C0n57an71n** [comment]
> @C0n57an71n so are you saying that it is fixed, or not ;)

I'm just saying that the issue with video freezing while recording had never happened on my Hammerhead, regardless if was OTA11, 12 or 13. It is still present the bug that apear when changing from photo to video and viceversa, but the actual bug report it isn't about that, is it?

**Comment by laborim** [comment]
Device: Oneplus 3
Channel: rc
Build: 2020-W35/2

I can reproduce the error:
"App freezes and video cannot be made"

**Comment by dano6** [comment]
I can confirm that video recording does work on Nexus 5
@laborim Oneplus 3 has different issue
