### ISSUE TITLE
Docviewer unable to open shared documents via content-hub

### ISSUE THREAD

**Issue by FlavioMala** [ubports/ubuntu-touch#1647]
Problem-REPORT

- Device: BQ E5
- Channel: dev
- Build: "646" 19 Jan 2021

Today, after update from "645" (05 Jan 2021), opening some pdfs the message "error   the file does not exist" appears.
![screenshot20210120_013620329](https://user-images.githubusercontent.com/50835740/105111131-88300080-5ac0-11eb-89ea-f28a19e7a735.png)

There were already problems starting a couple of months ago with some pdfs: they did not open and the page remained blank (this also with pdfjsviewer).

No problem with other pdf file readers (e.g. Sturm reader), including "Libertine“ ones (Atril, document viewer, etc.).

Note: Mk, kb or number of pages...doesn't matter

**Comment by dobey** [comment]
What version of document viewer app do you have installed? It seems like you need to upgrade.

**Comment by FlavioMala** [comment]
From terminal:
![screenshot20210120_190721873](https://user-images.githubusercontent.com/50835740/105217497-3769e780-5b54-11eb-8fd5-d97bf5994209.png)
From OpenStore:
![screenshot20210120_191339585](https://user-images.githubusercontent.com/50835740/105217585-56687980-5b54-11eb-9afc-75f03ca59977.png)
...but I see a new update available:
![screenshot20210120_191859921](https://user-images.githubusercontent.com/50835740/105218367-587f0800-5b55-11eb-8143-dde7b9c047e3.png)
I will update and text...

**Comment by FlavioMala** [comment]
..."Nada"...
![Uploading screenshot20210120_193007614.png…]()

**Comment by FlavioMala** [comment]
A pdf (which causes the error) can be downloaded here:
https://www.iliad.it/docs/prezzi-599.pdf

**Comment by FlavioMala** [comment]
Another info: since the "white screen" problem appeared (1/2 months), by downloading a pdf and then opening it from the download screen, then scrolling pages / reading / etc. for several minutes, then when you return to the browser which still shows (it seems) the download page, this is "strange": it is out of focus, as if it were a fake copy, not real. And in fact by clicking on < at the top to return to the browser page where the pdf was downloaded, the browser crashes and resets with a blank page.
(Any other open pages / instances of the browser also crash and are closed.)

**Comment by dobey** [comment]
> A pdf (which causes the error) can be downloaded here:
> https://www.iliad.it/docs/prezzi-599.pdf

This PDF works fine for me on my Nexus 4 with docviewer 2.3.541

**Comment by FlavioMala** [comment]
Ch "dev"? Or "stable"?
Anyway I have reinstalled doc viewer ... No changes.

I have the feeling that the error appears in place of the white screen, with those pdfs where the problem was ...

**Comment by FlavioMala** [comment]
I don't know if related to Qt 5.12 migration...
I discovered that the pdf is opened if it is already present in the docviewer doc list (click on <above). See photo

**Comment by FlavioMala** [comment]
Note that:
-Deleting cache and other data with UT Tweak Tool have no effect on the list (still "populated")
-Deleting the list (all, do it in docviewer app) do not solve the problem.

**Comment by dobey** [comment]
> That is, it seems a problem of import, rather than of reading / opening.

Ah, OK. Looks like there's indeed an issue with importing a document using content-hub here.

**Comment by dobey** [comment]
OK, I've found the cause of this. It's due to changes in Qt and how it uses temporary files to do atomic copies, and the profile generated from apparmor is not compatible with that. In order to fix, we need to patch the code in `python3-apparmor`. So it may take a bit more time to get a fix for this, as we're currently relying on the apparmor packages from upstream Ubuntu.

**Comment by mardy** [comment]
> It's due to changes in Qt and how it uses temporary files to do atomic copies, and the profile generated from apparmor is not compatible with that.

Can you please detail what exactly did change? I've had a look at the bugreports.qt.io site, and found [reports](https://bugreports.qt.io/browse/QTBUG-27601) of `QFile::copy()` creating temporary files since 2012. Also, if someone who can reproduce the bug was so kind to show what is the error reported by apparmor (by running "`grep DENIED | /var/log/syslog`" after the issue has occurred). :-)

**Comment by FlavioMala** [comment]
"Yes Sir!"
So in a termilal:
grep DENIED /var/log/syslog > /home/phablet/Documents/pluto.txt
But pluto.txt it is very very very long, so pluto2.txt (attached) is a shorter form.
I think the "salient" part is from "Jan 30 11:13:01" to "Jan 30   ##11:13:05".
[pluto2.txt](https://github.com/ubports/ubuntu-touch/files/5897884/pluto2.txt)

**Comment by FlavioMala** [comment]
Note:
pluto.txt/pluto2.txt with devel 654 29 Jan (see below).

I have now upgraded to 655 30 Jan and tried again: no difference.
![screenshot20210130_132330551](https://user-images.githubusercontent.com/50835740/106356339-37f64100-62ff-11eb-9852-568e1bf278ea.png)

I accidentally discovered this (devel 655 30 Jan) if I go to "Documents" where I saved the files I can open them with docviewer! The files remain in the list:
![screenshot20210130_131817928](https://user-images.githubusercontent.com/50835740/106356462-0a5dc780-6300-11eb-8964-4623dc4d0ca6.png)

So I tried to copy a pdf from "Downloads" to "Documents" and docviewer can open it!
![screenshot20210130_133657785](https://user-images.githubusercontent.com/50835740/106356524-7c361100-6300-11eb-98f6-bf9a7b7d07c9.png)

Permission problem? (But OdfjsViewer can't)

**Comment by dobey** [comment]
> Can you please detail what exactly did change? I've had a look at the bugreports.qt.io site, and found [reports](https://bugreports.qt.io/browse/QTBUG-27601) of `QFile::copy()` creating temporary files since 2012. Also, if someone who can reproduce the bug was so kind to show what is the error reported by apparmor (by running "`grep DENIED | /var/log/syslog`" after the issue has occurred). :-)

It's changes to how QTempFile works. I don't have the specifics, but it's using `link()` syscall for part of the process. The generated profile by easyprof though only allows `rwk` and not linking. In debugging the issue, I had to chase some bits down applying a couple other workarounds, before the real denial issue appeared in syslog.

**Comment by dobey** [comment]
Should be fixed by https://gitlab.com/ubports/core/packaging/apparmor/-/merge_requests/1

**Comment by FlavioMala** [comment]
At the moment it is still present.

What I don't understand is the reason why if I move the pdfs to "Documents", docviewer manages to open them!
And in "Downloads, Videos, Pictures"... No!
![screenshot20210202_091931156](https://user-images.githubusercontent.com/50835740/106571931-12a04780-6538-11eb-85cb-bda8e4c4ce2f.png)

**Comment by dobey** [comment]
> What I don't understand is the reason why if I move the pdfs to "Documents", docviewer manages to open them!
> And in "Downloads, Videos, Pictures"... No!

Because, docviewer has read permissions for Documents folder and isn't copying the file via content-hub, while opening from file manager results in the file being copied to `Documents/Imported/` folder, which is getting blocked by apparmor, due to changes in Qt about how it copies files. Thus the proposed fix is to alter the system to give proper permissions in apparmor, to deal with the Qt changes.

Once the fix is merged, it will then be available in the devel image on the following day. It is not merged yet, and this issue is still open. So there's no need to say it is still not working or post more screenshots. :)

**Comment by FlavioMala** [comment]
Ahh... OK.
Thank you very much, especially for the detailed explanation. Now everything is clear!

**Comment by dobey** [comment]
The fix has been merged and should appear in tomorrow's devel image.

**Comment by dadandalive** [comment]
I confirm that PDFs downloaded with Morph browser, can be subsequently opened and read with docviewer, both through Morph's download list, as through the File Manager (without moving files from the Downloads folder). Some PDFs still show up as white pages in docviewer, but this must be a docviewer's issue. Tested on Nexus 5 RC 2021-W10.
