### ISSUE TITLE
https://devices.ubuntu-touch.io/device/x605/

### ISSUE THREAD

**Issue by kbprasad79** [ubports/ubuntu-touch#1900]
Hi, UB Ports software says Lenovo X605 tablet is not supported, but web page https://devices.ubuntu-touch.io/device/x605/ says it is.

**Comment by luksus42** [comment]
It is not in the installer yet.
But you can install a build, following the instructions...

**Comment by capsia37** [comment]
The device is in the installer now, this issue should be solved.

**Comment by luksus42** [comment]
The installer maybe still not identfy the device by itself because it is authenticating itself as "msm8953" and not "X605".
Therefor users need to select the device manually from the list.
But I don't think that this little issue will be resolved.
