### ISSUE TITLE
Camera flash does not work

### ISSUE THREAD

**Issue by stekalb** [ubports/ubuntu-touch#258]
- Device: bacon
- Channel: devel
- Build: 147

## Steps to reproduce

1. Open camera app
2. activate flash
3. take a photo 

## Expected behavoir
Flashlight

## Actual behavior
no flashlight

## Logfiles and additional information

flashlight does work when activated from the battery indicator.

**Comment by rocky58** [comment]
No news about this issue yet?

**Comment by dark-eye** [comment]
This might be a camera app issue does the flash in the Tagger app works? is it working in video mode?

**Comment by NeoTheThird** [comment]
It works with the direct hardware calls from the flashlight indicator, but apparently not with the camera api.

**Comment by Ublublu** [comment]
I have also the camera flash not working on **FP2, channel stable, version=r3.**
- No flash with the camera application when taking a photo with flash selected.
- and outside camera app, the flashlight button does not work.

This is a recent FP2 with the new camera module.

**Comment by dv-ds** [comment]
What Ublublu said applies to me as well, word for word. I'll also note that the flash was working on the device when I tested it in Android, prior to installing UBports.

**Comment by NeoTheThird** [comment]
@Ublublu @dv-ds That's a different issue: #448

**Comment by Intrinsically-Sublime** [comment]
So here we are 2 years later and the flash still doesn't work on the Oneplus One. The torch does work from the battery menu so it seems that we do have access to the led to control it. What is the problem with getting it to work now? The Oneplus One is supposed to be the phone that has complete compatibility and yet the camera is unusable in low light or dark conditions.

**Comment by Flohack74** [comment]
It will be fixed in the Halium 7.1 port. We decided to not investiagte this further in the 5.1 Android base that was used. I know it is annoying but we are a small team, and updating the Android base container is a task with lots of things to be checked, to not introduce regressions. That said, there will be a porting hackathon around Christmas time, where we probably can fix the last issues and offer it for testing. Then still, it will take a few weeks to see if its stable.

**Comment by Intrinsically-Sublime** [comment]
Sorry I did not intend to come across entitled or rude. I was really just curious about the situation. I am glad to here things are moving forward and appreciate all the hard work. I would not be using a touchscreen device if it were not for your hard work (was recently forced away from feature phones due to local cellular carriers not supporting them). Being a foss Linux user for 12 years I am spoiled and can't use Android or Windows. From my reading it appears that OTA-15 is to be released soon and then OTA-16 in the first quarter of 2021, is OTA-16 using Halium 7.1? Also I am curious as to the release schedule as it pertains to Halium. It seems that Halium is based on Lineage ports and currently Lineage is two versions ahead. My question is, is there a reason why UT is still working on Halium 7.1 work when 9 appears to be available and soon another version? Again this is not insult but rather wanting to understand. Thanks in advance for any insight.

**Comment by Flohack74** [comment]
We are working on Android 9 support, but if a device works well with a certain Android/Halium base, we are not intending to upgrade it "just so". The old 5.1 ports were partially hackish, and so we want to take the devices to a new layer. But since Anroid 9 support would introduce some regressions now, 7.1 is the choice for the older devices.
The problem is not to have a Lineage version, the problem is the finnicky Android APIs that change in every version. We are far behind, yes, and ultimately I dont believe we can ever reach a current Android version in time. Instead we are hoping to get Android-free hardware sooner or later, where we can define the speed more or less.
Therefore the core team is not investing all time in porting races, only to find a new Android version under the Christmas tree as a bad gift ;)

**Comment by mariogrip** [comment]
Fixed by https://github.com/ubports/qtubuntu-camera/pull/15 

Its in devel right now :)

**Comment by Flohack74** [comment]
However, got 2 reports from Germany that its still not working ^^ but lets see.

**Comment by CristianSw** [comment]
Work on my bacon device. Thanks for fix.

**Comment by MenmuirMark** [comment]
Flash, focus and zoom are all working on my OPO Bacon (rc) now thanks :)

**Comment by josevidalrt** [comment]
it works well
device: bq e4.5 krillin
rc 2021-w18
