### ISSUE TITLE
OTA does not work on rc

### ISSUE THREAD

**Issue by stekalb** [ubports/ubuntu-touch#294]
- Device: bacon
- Channel: rc
- Build: r6

## Steps to reproduce

AFAIK rc on bacon is on r7 or r8. But when you are on r6 the update screen shows no available updates

**Comment by pixelr0** [comment]
same on fp2
channel rc
build r7
update doesn't find r8

**Comment by mariogrip** [comment]
Seems to be a "Ghost update", this should be fixed in next rc OTA

**Comment by pixelr0** [comment]
new rc image v9. i still can't update  (fp2 doesn't find r9)
what should i do? re-flash or go back to stable?

**Comment by pixelr0** [comment]
also trying to change the channel to "stable" doesn't work. i just get the spinner "searching for updates" but doesn't find anything and now on About page Software/OS entry is missing o_O

**Comment by pixelr0** [comment]
after restarting the phone, now the Software/OS entry in About page is back again, i can see rc v7 and in the Channel settings the "Release candidate" option is selected, but previously was "Stable" so apparently it actually didn't do anything? there is something really wrong with the channel settings

**Comment by pixelr0** [comment]
cat application-legacy-ubuntu-system-settings-.log

2017-10-20 14:10:38,500 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:10:38,589 - WARNING - Last frame took 41 ms to render.
2017-10-20 14:10:40,268 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:40,269 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:40,271 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:10:40,277 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:55,046 - WARNING - Last frame took 48 ms to render.
2017-10-20 14:10:55,212 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:10:55,244 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:10:55,289 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:55,289 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:55,289 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:10:55,291 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:56,753 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:56,754 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:10:56,754 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:10:56,754 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:11:05,633 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:11:05,633 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:11:05,634 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:11:05,638 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:13:04,480 - WARNING - QObject::startTimer: Timers cannot be started from another thread
2017-10-20 14:13:16,975 - WARNING - 404
2017-10-20 14:13:36,384 - WARNING - 404
2017-10-20 14:13:39,110 - WARNING - Releasing device model ..
2017-10-20 14:13:39,115 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:13:39,119 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:13:39,122 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:13:39,125 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:13:41,547 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:13:54,142 - WARNING - 404
2017-10-20 14:14:32,917 - WARNING - QQmlExpression: Expression file:///usr/share/ubuntu/settings/system/qml-plugins/about/DevMode.qml:94:30 depends on non-NOTIFYable properties:
2017-10-20 14:14:32,918 - WARNING -     StorageAbout::developerMode
2017-10-20 14:14:33,013 - WARNING - Last frame took 32 ms to render.
2017-10-20 14:14:41,141 - WARNING - Releasing device model ..
2017-10-20 14:14:41,149 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:14:41,153 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:14:41,155 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:14:41,158 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:14:49,892 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:14:50,008 - WARNING - Last frame took 40 ms to render.
2017-10-20 14:14:52,405 - WARNING - 404
2017-10-20 14:15:16,594 - WARNING - 404
2017-10-20 14:15:32,982 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:15:32,984 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:15:32,986 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:15:32,996 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:15:48,284 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:15:48,384 - WARNING - Last frame took 58 ms to render.
2017-10-20 14:15:49,984 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:15:49,986 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:15:49,987 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:15:49,990 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:16:02,673 - WARNING - Last frame took 77 ms to render.
2017-10-20 14:16:21,337 - WARNING - QQmlExpression: Expression file:///usr/share/ubuntu/settings/system/qml-plugins/about/DevMode.qml:94:30 depends on non-NOTIFYable properties:
2017-10-20 14:16:21,337 - WARNING -     StorageAbout::developerMode
Attempted to unregister path (path[0] = null path[1] = null) which isn't registered
2017-10-20 14:16:27,783 - WARNING - 'caller' is DEPRECATED. It has no effect.
2017-10-20 14:16:52,339 - WARNING - Last frame took 80 ms to render.
2017-10-20 14:18:15,183 - WARNING - Releasing device model ..
2017-10-20 14:18:15,192 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:18:15,197 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:18:15,199 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:18:15,202 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:19:08,994 - WARNING - QObject::startTimer: Timers cannot be started from another thread
2017-10-20 14:19:18,105 - WARNING - Last frame took 39 ms to render.
2017-10-20 14:19:23,695 - WARNING - Last frame took 45 ms to render.
2017-10-20 14:19:24,127 - WARNING - QQmlExpression: Expression file:///usr/share/ubuntu/settings/system/qml-plugins/about/DevMode.qml:94:30 depends on non-NOTIFYable properties:
2017-10-20 14:19:24,127 - WARNING -     StorageAbout::developerMode
2017-10-20 14:19:31,004 - WARNING - Releasing device model ..
2017-10-20 14:19:31,013 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:19:31,017 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:19:31,020 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:19:31,023 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.
2017-10-20 14:20:27,754 - WARNING - QObject::killTimer: Timers cannot be stopped from another thread
2017-10-20 14:20:27,756 - WARNING - QObject::startTimer: Timers cannot be started from another thread
2017-10-20 14:22:27,878 - WARNING - Attempted to deliver an event to a non-existent window, ignoring.
2017-10-20 14:22:27,884 - WARNING - <Unknown File>: QML Item: Cannot anchor to an item that isn't a parent or sibling.

**Comment by pixelr0** [comment]
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
qml: Page_QMLTYPE_40(0x14d78a8, "systemSettingsPage")"System Settings": In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead.
BrightnessItem::BrightnessItem(const QVariantMap&, QObject*) ubuntu.widi.supported: 1
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
2017-10-20 14:32:59,537 - WARNING - virtual void UpdatePlugin::Click::ManagerImpl::check() Can't check: invalid session token.
2017-10-20 14:32:59,679 - WARNING - Last frame took 66 ms to render.
2017-10-20 14:33:01,993 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:33:01,993 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:33:01,995 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:33:07,245 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:33:07,245 - WARNING - void UpdatePlugin::Image::ManagerImpl::handleUpdateAvailableStatus(bool, bool, const QString&, const int&, const QString&, const QString&) Got non-numerical version, ignoring.
2017-10-20 14:33:07,251 - WARNING - Failed to parse availableVersion: ""
2017-10-20 14:33:11,307 - WARNING - 404

**Comment by pixelr0** [comment]
**!WORKAROUND!** change channel to devel (this seems to work on fp2 at least) and then try to change back to RC

**Comment by pixelr0** [comment]
and now i can't go back to RC from devel, fp2/devel r183
to me changing channels seems partially defect

**Comment by stekalb** [comment]
on bacon it works now (at least update from r8 to r9 to r10 worked). Maybe can be closed.

**Comment by stekalb** [comment]
Does not work from r10 to r11 again

**Comment by stekalb** [comment]
For me there's no way to switch to rc. Neither from stable nor from devel the rc image is found (bacon)
log at [http://paste.ubuntu.com/25905728](url)

**Comment by mihaelmilea** [comment]
Device: turbo. I switched from devel to rc r12 and now r13 is available on https://system-image.ubports.com/ubports-touch/15.04/rc/turbo/ but in System Settings Updates I only get the spinner and then: Software is up to date.

**Comment by NeoTheThird** [comment]
I don't have a Pro 5, so i can't reproduce this issue. Can someone try to use the installer to re-flash without the wipe option? That will not result in data loss: https://github.com/ubports/ubports-installer/
