### ISSUE TITLE
Endless DNS requests for dash.ubuntu.com

### ISSUE THREAD

**Issue by vandys** [ubports/ubuntu-touch#327]
- Device: Nexus 5
- Channel: stable
- Build: (I'll dig it up if it matters.)

## Steps to reproduce

1. Get a tcpdump running on your Internet gateway, looking just at phone packets
2. Fire up your phone, but don't actually do any net surfing
3. Watch the DNS requests from your phone

## Expected behavoir

The phone should not be mindlessly, endlessly requesting name resolutions.
It appears that Canonical has removed the DNS name dash.ubuntu.com, and the
phone is trying to resolve this name every few seconds.  Not good for battery,
not good for data plans.

Unlike dash.ubuntu.com, daisy.ubuntu.com still resolves, and yet I also see the
phone doing DNS requests for this name at pretty frequent intervals.  If you're
in there, you might see about backing that off as well.  My best guess from searching
around is that it has something to do with crash reporting.

As a workaround, I put /etc/hosts entries to stub out both these names.  No dire
consequences yet.

Thanks!

**Comment by mariogrip** [comment]
Thank you for reporting!

We need to get this fixed asap @NeoTheThird

**Comment by mariogrip** [comment]
Fix pushed: https://github.com/ubports/thumbnailer/commit/ebf60cf14ad4ce71cdbe8221f98c4dac56b42ed5

**Comment by ernesst** [comment]
Hey, Just for information I've this behavior on my 15.10 rc phone, not on the 16.04 one.

**Comment by mgresko8** [comment]
Hello,

still not fixed on my BQ Aquaris E4.5 with OTA-3 installed.

I see lot of
ERROR: SSRegistry: SmartScopesClient.get_remote_scopes(): Failed to retrieve remote scopes from uri: https://dash.ubuntu.com/smartscopes/v2/remote-scopes: unity::ResourceException: /build/net-cpp-2WCYZi/net-cpp-2.2.0+15.04.20161108.2/src/core/net/http/impl/curl/request.h@221 - operator(): Couldn't resolve host name
messages in .cache/upstart/smart-scopes-proxy.log

Thanks

Marek

**Comment by Flohack74** [comment]
The smartscopes proxy will be deactivated in 16.04 - I am not sure we can release this on 15.04 though

**Comment by Flohack74** [comment]
BTW daisy.ubuntu.com belongs to whoopsie and apport crash reporting. We are considering also how to resolve this dependency.
