### ISSUE TITLE
Date/Time is at default value (year 1970) on every boot

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubuntu-touch#5]
https://launchpad.net/~blunoise reports:
Hi all,
when phone is rebooted it takes the default value from RTC , but RTC writes operations are disabled.

What i find is a rtc write protect on device tree.

In the file :
arch/arm/boot/dts/msm-pm8941.dtsi

the key ->

qcom,qpnp-rtc-write = <0>

is set to zero.

Regards

This has been confirmed on the FP2 and Nexus 5.

**Comment by peat-psuwit** [comment]
The fix should already be in the repo already. Not sure if devel_rc-proposed has them already.

**Comment by NeoTheThird** [comment]
Fixed :)

**Comment by ITwrx** [comment]
i have an nexus 5 (d821) running ubuntu touch 15.04 which still exhibits this issue.

**Comment by Flohack74** [comment]
Yes this is unfortunately true, even on rc. I moved it to OTA-3 since this will not make it into OTA-2 anymore :(

**Comment by ChloeWolfieGirl** [comment]
Also an issue on the opo

**Comment by Flohack74** [comment]
@rubencarneiro can we fix this with your workaround on all 3 devices?

**Comment by rubencarneiro** [comment]
On Hammerhead is fixed Now

https://github.com/ubports/android_device_lge_hammerhead/commit/8518fe8295dad55381fa9a29c5d34a3c9e1eb288

**Comment by Flohack74** [comment]
on OPO still exists in r195, but maybe the fix was not picked up by CI?

**Comment by rubencarneiro** [comment]
Can you se if the folder /data/time exist on system files?

**Comment by mariogrip** [comment]
We should try using the fixrtc that exist in the initrd instead of on the android side https://github.com/ubports/ubports-boot/blob/master/initramfs/scripts/local-premount/fixrtc

**Comment by mariogrip** [comment]
Fix released, created https://github.com/ubports/timekeeper that runs on ubuntu side instead of android side, this should be more reliable

**Comment by NeoTheThird** [comment]
Not fixed on N5.

**Comment by NeoTheThird** [comment]
Small typo: https://github.com/ubports/timekeeper/commit/ab57b1986c480cb302d9285c42402c14fb96868a

**Comment by Flohack74** [comment]
Fixed on N5 for me :)

**Comment by NeoTheThird** [comment]
I can confirm that.
