### ISSUE TITLE
Battery level stuck at 50% on OPO

### ISSUE THREAD

**Issue by teo693** [ubports/ubuntu-touch#533]
Hello Everybody,

I'm a new ubuntu touch user, and I've noticed a problem with the battery in my oneplus one,

First, the battery level shows 50% for a long time, after which the battery suddenly bursts out

Secondly, often after connecting the phone to charging, UT does not show that the phone is charging, so I do not know if anything is happening because the battery level is all the time 50%;)

My battery is not running out too fast. The cable is rather fine, because when I turn off the phone and I will connect to the charging cable, phone shows that it is charging, but when it is turned on it does not show. 

I just forgot to add that I have 15.04 stable UT, I did not manage to notice whether this problem occurred from the moment of installing UT, or after some of my interference in the UT. My only intervention in the system was after using the tutorial contained in this link https://forums.ubports.com/topic/1015/howto-opo-fix-mtp-driver-permissions, which on the occasion helped me to solve my problem (

I made this screen shoot this morning, and when UT was switch off, phone shows on the screen the battery is charged in 100%, but UT still showing 50%

I also noticed that UT constantly monitors the battery level, because over time it reduces the brightness of the screen. The question is why GUI stopped at 50% and does not want to update itself, since UT itself knows what is the current level of battery.
[https://forums.ubports.com/assets/uploads/files/1521271950720-screenshot20180317_072705972.png](url)

**Comment by NeoTheThird** [comment]
Thank you for reporting. I can not reproduce this, could you check if this issue is also present in Android? There might be a problem with your hardware...

**Comment by teo693** [comment]
Solved
Problem despaired after rebooting UT, so i don't know what happens.
Is there any log files in whitch i can check what cause this problem?
There wasn't any problem before on android, wright now i have only UT on my OPO.

**Comment by Flohack74** [comment]
We will close this for now... Problem is that all those issues are hard to debug, unless they affect all users. Ubuntu Touch relies fully on the underlying Android container for battery management and charging. In 16.04 we will update the repowerd with some improvements hopefully.

**Comment by dmaglio** [comment]
UT 16.04 (OTA-7) and i have the same issue, battery alway at 50%

**Comment by dmaglio** [comment]
UT 16.04 (OTA-8) and i have the same issue, battery alway at 50%

**Comment by Flohack74** [comment]
That is very strange. I will reopen this...

**Comment by Darklesss** [comment]
I'm having this same problem as well, exactly as described by teo693. Tried going back to LineageOS, and did not have the problem. When I reinstalled UT, it came back. Let me know if there are any logs or something I can share to help figure it out.

Thanks!

**Comment by mymike00** [comment]
Can someone please change the title? this issue doesn't affect 15.04 only...
Thanks

**Comment by Intrinsically-Sublime** [comment]
I can confirm this bug still happens randomly. I had just installed a new battery and on the same day I decided to switch over to the rc channel and few hours later the battery was stuck at 50%. I left it for a few hours thinking it may have just been the system relearning the capacity when it suddenly shut off. I then tried to charge the phone while it was off but gave up and reinstalled the old battery and reverted back to the stable channel since I wasn't sure where the issue was coming from.

**Comment by Llazcanoster** [comment]
In my case, I also confirm this bug that has been happening to me for years.  The battery indicator works and stops working randomly, setting to 50% and without indicating whether it is charging or not.  Sometimes it is fixed with a few reboots.  It happened to me with the original battery and with a replacement Nohon.  I have also tried different update channels and going back to Android and confirming its correct operation there

**Comment by ChefGoldblum** [comment]
Can confirm this is still happening. I noticed my battery wasn't quite holding a charge anymore, so I bought a new one. After swapping it out, I would notice that it was stuck showing 50% battery for a majority of the time. It also would not charge when plugging it in. Rebooting a few times usually fixes the issue.

**Comment by Flohack74** [comment]
Well batteries need to be calibrated after replacement. You can try to do this, at least let it shut down once or twice (I would not go for more repetitions due to the danger of drop the battery level too low): https://medium.com/@GadgetHax/how-to-properly-calibrate-the-battery-on-any-android-phone-962ee597f29e

**Comment by Flohack74** [comment]
And I also close this, since charging is done by the phone´s Android layer, which we do not mess with, and charging control in Ubuntu Touch is the same as in Android.
