### ISSUE TITLE
Bluetooth controls in car: Recent calls list not accessible

### ISSUE THREAD

**Issue by abkro** [ubports/ubuntu-touch#650]
- Device: Nexus 5 - hammerhead
- Channel: Xenial - Devel - 16.04.
- Build: 410

### Steps to reproduce
Switch on bluetooth and establish connection to car media system. Bring up phone via car controls. Choose "recent calls".

### Expected behavior
On the car's display, a list of the most recent calls appears in reverse chronological order. One should be able to select a call from the list in order to place a new call to the same party.

### Actual behavior
The display shows no recent calls. Empty display.

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2068439/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2068440/UTlogcat.txt)

This behavior was the same on my BQ Aquaris E4.5 with Canonical's Ubuntu Touch back in the day. I will check it again on build 412, which I have now installed, and report in a comment below.

Note: Browsing the device's contact list in the car over the bluetooth connection works as it should.

**Comment by Flohack74** [comment]
The question is here, what is the behaviour in the upsteream Bluez library, and if this functions ever exposed by it.

**Comment by abkro** [comment]
> The question is here, what is the behaviour in the upsteream Bluez library, and if this functions ever exposed by it.

Not sure what you mean by "and if this functions ever exposed by it"?

**Comment by abkro** [comment]
Today, using Nexus 5/hammerhead running Xenial r413, I confirmed this behavior in a different car of a different make. Same result.

**Comment by Flohack74** [comment]
@abkro The bluetooth stack is not an invention of UBports or Canonical. Its using the Bluez stack http://www.bluez.org/ for all that. So the question is, is Bluez in the version that you currently have on your phone even capable of sending the last calls list? Thats the first question to ask here.

**Comment by Flohack74** [comment]
The current Bluez version in Ubuntu 16.04 is 5.37-0ubuntu5.1 - Its not only what is in the kernel, but around the bluetooth driver there is a bunch of userspace applications that need to handle that. Another good candidate is the connection between Bluez and oFono, which is the part which serves the telephony functions in UT. So there are some good items for research, if and how this function is programmed into UT. Because I myself have never seen the call history working on UT, not even on 15.04 :).
But probably we need to verify this: https://github.com/pauloborges/bluez/blob/bc704506e69ae30b0770aac32504e89cf2dc9ddf/doc/obex-api.txt#L318

**Comment by mariogrip** [comment]
I have pushed the latest version (5.50) of bluez to xenial_-_new-bluez please try this to see if it fixes the issue :)

`sudo ubports-qa install xenial_-_new-bluez`

**Comment by Smirftsch** [comment]
As of now on my VollaPhone this problem still exists.

Device: Volla Phone
Channel: RC
Build: 2022-W02 (Ubuntu 16.04), also tried on stable version.)
