### ISSUE TITLE
[xenial] google calendars not displayed with their names and calendar list on event creation incomplete

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubuntu-touch#762]
- Device: Turbo
- Channel: RC
- Build: 4

### Steps to reproduce
Install calendar and sync calendar with google calendar account.
- Open calendar app and open "Calendars view".
- Select a calendar when creating an event

### Expected behavior
- To see only each google calendar synced and listed by its name.
- See all the calendars listed (on event creation)

### Actual behavior
- All the google calendars are titled with the email address (see attached image).
- Only a subset of the available calendars are shown (when selecting calendar for event creation)

**Comment by hummlbach** [comment]
@tomoqv that are most probably corpses in .config/evolution/sources. I hope you only got them from beta testing...  Deleting .local/share/evolution/calendar, .cache/evolution/calendar and the files having something to do with google calendars from .config/evolution/sources followed by a reboot should solve that.

**Comment by tomoqv** [comment]
Thanks @hummlbach 
I deleted `.local/share/evolution/calendar` and `.cache/evolution/calendar`
and rebooted, but same problem. My` .config/evolution/sources` contains a lot of files like the following, should I delete all those too?
```
1530998652.4322.5@ubuntu-phablet.source
1530998652.4322.6@ubuntu-phablet.source
1530998652.4322.7@ubuntu-phablet.source
1530998652.4322.8@ubuntu-phablet.source
```

**Comment by hummlbach** [comment]
You can delete all of them if it doesn't hurt you (namely if you don't store calendars locally). Or judge by their content (they are textfiles) which ones have something to do with Google (I.e. you should find the server or username inside...)

**Comment by tomoqv** [comment]
Ok, deleted them too, but not completely solved. I still get six instances of the same calendar. Also, some of the events I can't edit or delete.
![screenshot20180711_233255721](https://user-images.githubusercontent.com/13762919/42600561-17246c76-8563-11e8-9711-8d041a0af0ac.png)

**Comment by hummlbach** [comment]
Make sure to delete all the listed directories above and reboot afterwards. @malditobastardo had the same symptoms and we solved it that way... Are you sure that doesn't help in your case?

**Comment by tomoqv** [comment]
I have started to dig deeper into this. I have logged into my google calendar on the pc and found some strange things in the "Birthday" calendar. However, I see some all day events that I have added to a certain date in google that show up one day later in the UT calendar. Also, I don't the calendars I got on 15.04 which are shown below.
Yes, I just deleted everything mentioned above and rebooted phone. Then deleted google account and readded it. Something is really fishy here. I also see some peculiarities in the contacts app, that suddenly don't sync all of my contacts, but probably not related to the calendar issues here.

![google calendars](https://user-images.githubusercontent.com/13762919/42601364-b2421c7e-8565-11e8-9868-9f825b1ad30e.png)

**Comment by tomoqv** [comment]
When I click on the all day event in the UT calendar for Tuesday 17 July, it reads 16 July (all day). That seems like a bug. Still doesn't explain why I can't see all my calendars and why UT calendar keeps adding duplicate instances of my main google account.

**Comment by hummlbach** [comment]
What i can confirm (on mako@dev18.07.07) is
- google calendars are displayed with the email address and not with their names
- on creating a new event it does not show all calendars (sometimes more, sometimes less calendars are shown, but usually not all, also the local calendar does not show up...)

Syncing in both directions seems to work and all day events are shown at the right date here, so i can not confirm that... @tomoqv can you please double check that?

**Comment by tomoqv** [comment]
@hummlbach 

> In principle syncing in both directions seems to work and all day events are shown at the right date here, so i can not confirm that... @tomoqv can you please double check that?

Which time zone are you in? There is definitely something fishy going on with regards to the time. When I once more have deleted all files and my google account and readded it and synced, my timed events are two hours off, but my all day events show up on the correct date. I am on CET, i.e. UTC+2.

It seems also that a new sync is not triggered until google account is deleted and added back again.

**Comment by hummlbach** [comment]
I'm also on CET and i don't see that. So please check your timezone settings on google and the phone. And if you're realy sure its a bug, please open another issue.

**Comment by tomoqv** [comment]
Timezone Stockholm UTC+2
I will file a separate bug for this.

**Comment by NeoTheThird** [comment]
Was this an issue on vivid as well?

**Comment by hummlbach** [comment]
This one https://github.com/ubports/calendar-app/issues/42 once reported in the calendar tracker sounds pretty much like this. But it does not happen on my turbo@15.04. (just tried it)

**Comment by mardy** [comment]
I noticed the same issue when creating a Nextcloud calendar: it gets listed twice.

I'll investigate :-)

**Comment by mardy** [comment]
Update after a few minutes of investigation: from the `sync-monitor` logs it appears that we actually know the calendar names (I can see them in the log). Then sync-monitor [tries to store the data into a QOrganizerCollection](https://github.com/ubports/sync-monitor/blob/calDav/src/eds-helper.cpp#L48), which is part of the QtPim module; the operation succeeds, but obviously the `QOrganizerCollection::KeyName` detail gets lost.

I fear that this is due to not having the latest QtPim with our Ubuntu-specific changes; a few months ago I tried to update it, but the update got reverted because it was causing serious issues. I'll try to resurrect that work.

**Comment by mardy** [comment]
Here's a proposed fix, please review (and merge once approved): https://github.com/ubports/address-book-service/pull/2

**Comment by hummlbach** [comment]
@flohack this fix should actually already be in the images on the development channel, right? (asking, since my Google test calendars are still listed with the account name instead of the calendars names... [mako todays devel 130])

**Comment by mardy** [comment]
@hummlbach note that you need to disable and re-enable the calendar switch in the Accounts page in System Settings, in order to forcibly refresh the calendar list.

**Comment by hummlbach** [comment]
@mardy I did that. I even cleaned up the evolution cache and config directories, rebooted and added another account. So either the fix has not yet made it into the mako image or somehow doesn't work for me. I tried it with Google and a sago server using caldav.

**Comment by mardy** [comment]
@hummlbach what do you get if you type this in the console?

    apt-cache policy evolution-data-server-utouch

**Comment by hummlbach** [comment]
Seems to be not up to date:

phablet@ubuntu-phablet:~$ apt-cache policy evolution-data-server-utouch
evolution-data-server-utouch:
  Installed: 0.1.3+ubports+0~20180106100018.1~1.gbpc78730
  Candidate: 0.1.3+ubports+0~20180106100018.1~1.gbpc78730
  Version table:
 *** 0.1.3+ubports+0~20180106100018.1~1.gbpc78730 100
        100 /var/lib/dpkg/status

**Comment by Flohack74** [comment]
I think our clickbuilder is not building automatically right now. A manual build/push to Openstore would be useful.

**Comment by mardy** [comment]
@Flohack74 why clickbuilder? This is not a click package.

**Comment by Flohack74** [comment]
Oh you are right :) - let me take a look then....

**Comment by Flohack74** [comment]
Well it is in the pool: http://repo.ubports.com/pool/xenial/main/a/address-book-service/ - you might want to check if those debs have landed in latest devel images...

**Comment by mardy** [comment]
@Flohack74, as I wrote [here](https://github.com/ubports/ubuntu-touch/issues/762#issuecomment-414084213) it's not in the rootfs, hence my question: how can we bring it into the rootfs? I thought that it would all happen automatically, but it looks like something went wrong?

**Comment by Flohack74** [comment]
If it is in this list it should get installed automatically from our repo server: https://github.com/ubports/ubuntu-touch-meta/blob/xenial/touch-armhf - So its not there, no install :P - was this installed before? (Canonical image)

**Comment by mardy** [comment]
Wait, the problem is not about the package not being installed: it is indeed installed (so, we don't need to add it to the meta file), but the problem is that it's not the latest version. Maybe it's because I didn't add a changelog entry?
Can you please have a look at this? https://github.com/ubports/address-book-service/pull/4

**Comment by Flohack74** [comment]
If it is installed but not in meta then its not the version from CI - can you send me output that you get for dpkg info about it?

**Comment by mardy** [comment]
It was pasted a few comments above :-)
https://github.com/ubports/ubuntu-touch/issues/762#issuecomment-413782037

**Comment by mardy** [comment]
@hummlbach could you please try the latest image and see if it's fixed now? I see that the latest rootfs contains the new package. :-)

**Comment by hummlbach** [comment]
@mardy well done! Seems to be fixed. @tomoqv can you please also confirm that it works for you.

**Comment by tomoqv** [comment]
Sorry, I have got lost in all the comments here. What am I supposed to confirm? That I see my calendars by name? I still don't on RC 2018-W35.

**Comment by hummlbach** [comment]
@tomoqv: You shall confirm, that account sync is now working properly. ;-) You eventually have to delete `.config/evolution/sources` as described above.

**Comment by tomoqv** [comment]
Yes, synchronization with google calendar works for me (both ways), but all my calendars still show as only the account gmail address.
