### ISSUE TITLE
Impossible changing default Calendar

### ISSUE THREAD

**Issue by LlamasJM** [ubports/ubuntu-touch#919]
<!I tried to change from one account to another, into «Configuration». But when I go out of app and enter again, account hasn't changed. I'm on OTA-5

Thank you for wanting to file an issue! If you have a minute, please take the time to read our guide on writing a good bug-report:

    https://docs.ubports.com/en/latest/contribute/bugreporting.html

If not and you just want to get this over with, that's also quite alright. But please try to format your issue correctly, to make it easier for us to read. Below, we provide a template for a feature-request and a bug-report. Use common sense to determine what category your issue falls under and delete the template you don't need. Also, you don't need to stick to the templates under all circumstances. If you don't need a heading, remove it. If you think a new section will provide valuable information, add a new heading. We're not dogmatists, we're pragmatists who just want to be able to efficiently work with new issues.

--------------------------------------------------------------------------------
------------------------------------------------------------------------------->

### Illustrations

I tried to change from one account to another, into «Configuration». But when I go out of app and enter again, account hasn't changed. I'm on OTA-5

- Device: Fairphone 2
- Channel: OTA-5 stable
- Build:Ubuntu 16.04

### Steps to reproduce
- Make sure you have some online calendar in addition to the preconfigured Personal calendar
- Open the settings menu, change the default calendar
- Restart the app, open the settings menu again

### Expected behavior
When I change an account in Calendar, I expect this to be saved

### Actual behavior
Account is always the same, impossible changing

**Comment by MK1973** [comment]
I can confirm the issue, there are really two weird behaviour, at least in my case: 

1. when default UT personal calendar is marked and set-up, it is impossible to change or switch to any other online calendars even they have been added previously with the green checkmarks in the settings screen. 

Note: To add new online calendars click on the first rectangular icon that appears on the top side of opened calendar app. 

The reason is that the scroll menu does not open. It looks like not allowed. 

2. when default personal calendar is unmarked, than it is possible to switch to another online calendars but the new selected online default calendar does not remain, it is not saved. As default is set by the system the Birthday and Anniversary/next first position in calendars list setting page.

**Comment by MK1973** [comment]
In accordance to Lionelb: 

It has been commented a lot and we are trying to let people know. It seems to be happening universally from 15:06

**Comment by mardy** [comment]
This has already been fixed in https://github.com/ubports/calendar-app
Someone please make a release of the click :-)

**Comment by hummlbach** [comment]
Hum... Published new click, but still doesn't work...(?)

**Comment by mardy** [comment]
It looks like I never released the updated qtorganizer-eds5. I've tagged 0.1.4 now, so hopefully tomorrow's image will have this fixed.

**Comment by mardy** [comment]
Tomorrow's daily image should contain version 0.1.5, that should finally fix the issue for real :-)

**Comment by UniversalSuperBox** [comment]
Closing for QA, please test that this is fixed.

**Comment by ferrettim** [comment]
device:Nexus 5
channel: RC 2018-W48
issue not solved: tested both with Nextcloud and a genera CalDav account. After sync, calendars show in the Default calendar listing but calendar default is not saved.

**Comment by LlamasJM** [comment]
Same here. Same channel, device Fairphone. And I can't choose a day - hour to add anything, from calendar. I must add new event and change day - hour into the event. Not solved...

**Comment by hummlbach** [comment]
You need the beta calendar click posted in QA telegram group for that.
