### ISSUE TITLE
camera app freezes after taking some pictures (in quick sequence?)

### ISSUE THREAD

**Issue by hummlbach** [ubports/ubuntu-touch#959]
- Device: mako
- Channel: devel
- Build: 2018-11-20

### Steps to reproduce
- take some photos

### Expected behavior
- photos are taken

### Actual behavior
- after some photos have been taken the camera app freezes
- phone needs to be restarted to use the camera app again

### Logfiles and additional information
- i will add some later

@Flohack74 gave the hint, that this may be a duplicate of #932

**Comment by Danfro** [comment]
#915 and #908 likely related

**Comment by Thieb67k** [comment]
I have the same random problem.

    Device: LGE Nexus 4
    Channel: stable
    OTA-5

**Comment by raoulsalan** [comment]
I had the same problem on my nexus 5 and i found 2 solutions
1.massage your phone on the camara area . and it works .
2. unplug and replug camaras

**Comment by WillemHexspoor** [comment]
I can't reproduce on a Mako on the devel channel currently running OS build 2018-12-08. The phone cam take around 60 pictures in 30 seconds without issues.

**Comment by Danfro** [comment]
As with rc 2018-W50 on my E5 I do not have problems with taking many photos anymore (closed my issue #915).
@hummlbach  Is it still the same on your device?

**Comment by Danfro** [comment]
Ah, I do only very rarely use the front camera. I will have to check if this is a kind of face recognition. :-)
I found when testing things are sometimes ok. Real life will tell if it will happen again. It generally was on a trip out when you take photos, open this app, open that app. Maybe I should try a much harder testsetup...

**Comment by Thieb67k** [comment]
I can add to my previous comment that my camera app freeze after the 1st picture.
My screen is black and cannot go to the pictures manager or take another picture.
Restart the app doe not help: One solution-->Restart the phone!
It is not often but that happens, and it is very annoying.

**Comment by m0n5t3r** [comment]
Nexus 5 here, app freezes after the first photo, works again after a while. Video doesn't work at all (screen freezes, video is all black in the camera app and won't open when accessed from the gallery).

**Comment by Flohack74** [comment]
That should be solved for hammerhead (Nexus 5) now ;)

**Comment by m0n5t3r** [comment]
yup, I can confirm it works; video is still broken, but stills are fine now :)
